"""Output formatters — SRT captions, plain-text transcript, and show notes."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from screen_time_saver.models import Digest, TimestampedSegment


# ── Helpers ───────────────────────────────────────────────────────


def _ms_to_srt_time(ms: int) -> str:
    """Convert milliseconds to SRT timecode ``HH:MM:SS,mmm``."""
    hours, ms = divmod(ms, 3_600_000)
    minutes, ms = divmod(ms, 60_000)
    seconds, ms = divmod(ms, 1_000)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{ms:03d}"


def _ms_to_short(ms: int) -> str:
    """Convert milliseconds to ``[MM:SS]`` display timestamp."""
    total_seconds = ms // 1000
    m, s = divmod(total_seconds, 60)
    return f"[{m:02d}:{s:02d}]"


# ── Public API ────────────────────────────────────────────────────


def generate_srt(
    segments: list[TimestampedSegment],
    output_path: Path,
) -> Path:
    """Write an SRT subtitle file from *segments*.

    Returns the written file path.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []

    for idx, seg in enumerate(segments, start=1):
        lines.append(str(idx))
        lines.append(f"{_ms_to_srt_time(seg.start_ms)} --> {_ms_to_srt_time(seg.end_ms)}")
        lines.append(seg.text)
        lines.append("")  # blank separator

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def generate_transcript(
    digest: Digest,
    segments: list[TimestampedSegment],
    output_path: Path,
) -> Path:
    """Write a clean, timestamped plain-text transcript.

    Returns the written file path.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "SCREEN TIME SAVER — Daily Digest",
        f"Generated: {digest.generated_at:%Y-%m-%d %H:%M}",
        f"Title: {digest.title}",
        "=" * 50,
        "",
    ]

    # If we have timed segments, embed timestamps.
    if segments:
        for seg in segments:
            lines.append(f"{_ms_to_short(seg.start_ms)}  {seg.text}")
    else:
        lines.append(digest.full_script)

    lines.append("")
    lines.append("=" * 50)
    lines.append("Sources:")
    for section in digest.sections:
        lines.append(f"  - {section.source_name}: {section.source_url}")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def generate_show_notes(
    digest: Digest,
    output_path: Path,
) -> Path:
    """Write Markdown show notes suitable for podcast or YouTube descriptions.

    Returns the written file path.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    now = digest.generated_at or datetime.now()

    lines: list[str] = [
        f"# {digest.title}",
        "",
        f"*Generated by Screen Time Saver on {now:%Y-%m-%d}*",
        "",
        "---",
        "",
    ]

    for section in digest.sections:
        lines.append(f"## {section.headline}")
        lines.append("")
        lines.append(section.summary)
        lines.append("")
        if section.key_points:
            for point in section.key_points:
                lines.append(f"- {point}")
            lines.append("")
        lines.append(f"Source: {section.source_url}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "*This digest was AI-generated from public social media content. "
        "Support the original creators by visiting their pages!*"
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path
